### ISSUE TITLE
routes.js issue

### ISSUE THREAD

**Issue by timurcatakli** [ReactjsProgram/React-Fundamentals#1]
<IndexRoute component = {Home}> </Route> is throwing error
<IndexRoute component = {Home}></IndexRoute> seems to fix the problem.
Opened a pull request about it.

Thank you.

**Comment by tylermcginnis** [comment]
Hi. Did your description get messed up?

**Comment by animsaj** [comment]
when I try to run npm run prod it throws an error. following debug file:
![screenshot from 2016-03-29 09 00 13](https://cloud.githubusercontent.com/assets/9598025/14099273/b1b7f71c-f58c-11e5-87a3-45d03af36056.png)
