### ISSUE TITLE
Update to Copy Plugin 

### ISSUE THREAD

**Issue by mradzwilla** [ReactjsProgram/React-Fundamentals#102]
Hey, just leaving this as a comment to update the course docs and to help anyone else who gets stuck here. The Copy Plugin used in the "Hosting With Netlify" has been updated and the Copy Plugin code should now be:

`    new CopyPlugin({
      patterns: [
        { from : '_redirects' }
      ]
    })`

**Comment by tylermcginnis** [comment]
Thanks! Will get an update out soon.
