### ISSUE TITLE
Video 11

### ISSUE THREAD

**Issue by caiohamamura** [ReactjsProgram/React-Fundamentals#15]
While you are testing if the loader component is working you go back to the Container (both ConfirmBattle and Results) and change the setState to be always true.

Wouldn't it be better to just change the shorthand that checks if it isLoading? Such as:

`function ConfirmBattle (props) {

```
return props.isLoading || true

? <Loading />

: ...` 
```

Just a suggestion though, great videos, thanks a lot!

**Comment by tylermcginnis** [comment]
That would work as well. Though, not worth updating the videos for.
