### ISSUE TITLE
Webpack -p error in npm

### ISSUE THREAD

**Issue by erinjerri** [ReactjsProgram/React-Fundamentals#21]
I keep receiving this error message every time I try to run `npm run production`
`npm ERR! Darwin 15.0.0 npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "production" npm ERR! node v6.2.2 npm ERR! npm v3.9.6 npm ERR! code ELIFECYCLE npm ERR! react-boilerplate@3.0.0 production:webpack -p`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-boilerplate@3.0.0 production script 'webpack -p'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! webpack -p
npm ERR! You can get information on how to open an issue for this project with:
npm ERR! npm bugs react-boilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! npm owner ls react-boilerplate
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR! /Users/user/Desktop/react-boilerplate-master/npm-debug.log`

I've moved my config file to the correct directory, other folks tell me it's a shell error and to just run `npm run build` this doesn't quite work. What's going on? I can't get the dist folder to populate. Help!`

**Comment by thang-lai** [comment]
Hi, I got the same error here. Took me 1 hour plus to find out that was the typo in webpack.config.js file.
In 'loaders', make sure:  loader: "babel-loader", not  loaders: "babel-loader" as in my case.

If you're not having this problem, just download the author's webpack.config.js file and do the file diff with yours, or run the author's file first to see if it works.

**Comment by tylermcginnis** [comment]
Closing since this is most likely an issue with your code. Double check that in this repo. If you're still having issues, DM me in the Slack channel.

**Comment by erinjerri** [comment]
Ah ya it was mostly basic syntax errors I caught.

On Sat, Jun 25, 2016 11:54 PM, Tyler McGinnis notifications@github.com wrote:
Closing since this is most likely an issue with your code. Double check that in
this repo. If you're still having issues, DM me in the Slack channel.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub , or mute the thread .

Erin Pangilinan erinjerri16@gmail.com
