### ISSUE TITLE
Video3 branch has a different code

### ISSUE THREAD

**Issue by lporras** [ReactjsProgram/React-Fundamentals#23]
Hey @tylermcginnis,

I'm following the React Fundamentals course, I'm currently on this [lesson](http://courses.reactjsprogram.com/courses/reactjsfundamentals/lectures/760335), now the lesson's description points to video3 [branch](https://github.com/ReactjsProgram/React-Fundamentals/tree/video3), but it has different code from the actual video.  While the video shows an example about creating an avatar component using User's Data from a JSON, the branch's code has a Container with a Wrapper component.

**Comment by tylermcginnis** [comment]
Awesome thanks! Going to hopefully get to this in the next week or so.
