### ISSUE TITLE
/playerOne route not working

### ISSUE THREAD

**Issue by artitudinale1** [ReactjsProgram/React-Fundamentals#27]
I checkout this brunch and /playerOne route seems not to working.
I have this error: 

`index_bundle.js:20302 Warning: [react-router] Location "//playerOne" did not match any routes`

**Comment by tylermcginnis** [comment]
Is your URL formatted like this with /playerOne after the random hash?

http://localhost:8080/#/?_k=pntbhs/playerOne

If it is try placing it before like this,

http://localhost:8080/#/playerOne?_k=pntbhs

**Comment by artitudinale1** [comment]
Yep- like that works! Thanks

**Comment by tylermcginnis** [comment]
👍🏻

**Comment by stern-shawn** [comment]
Thanks for covering this, just ran into this issue myself!

**Comment by tylermcginnis** [comment]
@stern-shawn I need to make a note about it on the vid. Not sure what changed in the router but pops up all the time now :/

**Comment by marshallmurphy** [comment]
Ran into the same issue, thanks for clearing it up!

My problem now is that while I see the header, input, and button, none of it is styled with bootstrap.

Should I be including jquery and the bootstrap.min.js CDNs somewhere that I am missing? 
(Note- I tried including those in the index.html (both) to no avail.)
