### ISSUE TITLE
The Bootstrap CDN now requires an integrity hash

### ISSUE THREAD

**Issue by coaxial** [ReactjsProgram/React-Fundamentals#30]
If you're going to use the Bootstrap CDN to get the CSS, the integrity hash is now mandatory:

``` html
<link
      href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
      crossorigin="anonymous">
```

Without it, the file isn't served and a 403 is returned instead.

**Comment by kayakr** [comment]
Confirm that above patch changes CDN response from HTTP 403 to HTTP 200.

**Comment by coaxial** [comment]
It worked for me, and it's from [bootstrapcdn.com](https://www.bootstrapcdn.com/) (under CSS)

**Comment by YannHulot** [comment]
I am currently using this CDN: https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css 
and do not need any hash.

**Comment by tylermcginnis** [comment]
Hi! Thanks for filing this. As of tomorrow morning, the entire course will have been re-built and re-recorded from scratch. That means that this issue is no longer valid. Thanks again!
