### ISSUE TITLE
Video5. Redundant code line?

### ISSUE THREAD

**Issue by shurfee** [ReactjsProgram/React-Fundamentals#35]
Hi Tyler! Thank you for your course again, I like it very much.

In video 5 in ["PromptContainer.js"](https://github.com/ReactjsProgram/React-Fundamentals/blob/video5/app/containers/PromptContainer.js) you wrote the next line of code:
...
15. var username = this.state.username;
...

Is it necessary here? (Webstorm marked it as gray, it means inactive in my project. When I deleted this line from code, nothing changed - example still works).

Thank you!

**Comment by tylermcginnis** [comment]
It's a typo. I actually mean to use it below but instead I use this.state.username again rather than the username variable :/
