### ISSUE TITLE
TypeError: Cannot read property 'getCurrentLocation' of undefined

### ISSUE THREAD

**Issue by ejreed** [ReactjsProgram/React-Fundamentals#36]
Section: this.props.children and getting started with React Router 

I'm getting the subject error when trying to view the page. Looking at the index_bundle file and I see this:

```
 var history = this.props.history;
        var _props = this.props,
            routes = _props.routes,
            children = _props.children;

!history.getCurrentLocation ? process.env.NODE_ENV !== 'production' ? (0, _invariant2.default)(false, 'You have provided a history object created with history v2.x or ' + 'earlier. This version of React Router is only compatible with v3 ' + 'history objects. Please upgrade to history v3.x.') : (0, _invariant2.default)(false) : void 0;
```

I checked and had History 4.3.0. Even tried 3.2.1 and am still getting the error. 
Any thoughts?

**Comment by dewbjorn** [comment]
Same issue here. 
I've got the correct version of every module installed using npm, and I made sure the code is the same code used in the video.

Help?

**Comment by dewbjorn** [comment]
I think I got this.

Try running the prod script ('npm run prod'), or 'webpack -p'.

**Comment by JasnaTodorovic** [comment]
Seems to be an error in the current version of react-router. Going down to react-router 2.8.1 fixed it for me.

**Comment by ejreed** [comment]
@JasnaTodorovic that is what I did... went back to react-route 2.8.1 and it worked for me! 

Thank you!

**Comment by fspinnenhirn** [comment]
I've encountered the same error when using `react-router` **3.0.0.** 
Instead of downgrading the version, you can resolve this issue by changing your routes configuration (`config/routes.js`) as follows:

``` js
var hashHistory = ReactRouter.hashHistory;   // "import" hashHistory

var routes = (
  <Router history={hashHistory}>             // set the history property on the outer Router
    <Route path="/" component={Main}>
    ...
```

Tyler briefly shows similar code later in the video.

**Comment by ejreed** [comment]
@fspinnenhirn that worked for me on a new build! Thanks
