### ISSUE TITLE
After "npm run start" there is no application on "localhost:8080"

### ISSUE THREAD

**Issue by geyuqiu** [ReactjsProgram/React-Fundamentals#37]
but by running "npm run production", the index.html under dist/ does get updated
using     "react": "^15.3.2",
    "react-dom": "^15.3.2" as "dependencies" in package.json and other newest "devDependencies"

**Comment by geyuqiu** [comment]
This issue was created for branch video 2

**Comment by jbrz0** [comment]
In your webpack.config.js file you can add this option

```
  devServer: {
    contentBase: "./dist",
  },
```

**Comment by tylermcginnis** [comment]
Hi! Thanks for filing this. As of tomorrow morning, the entire course will have been re-built and re-recorded from scratch. That means that this issue is no longer valid. Thanks again!
