### ISSUE TITLE
Step1 branch and/or video1 branch missing

### ISSUE THREAD

**Issue by OZZlE** [ReactjsProgram/React-Fundamentals#43]
"If you do get stuck you can refer to the 'step1' branch."

There is no step1 branch or video1 branch..

React-Fundamentals$ git branch --all
* master
  remotes/origin/HEAD -> origin/master
  remotes/origin/gh-pages
  remotes/origin/master
  remotes/origin/sentry
  remotes/origin/solution
  remotes/origin/video10
  remotes/origin/video11
  remotes/origin/video12
  remotes/origin/video2
  remotes/origin/video3
  remotes/origin/video4
  remotes/origin/video5
  remotes/origin/video6
  remotes/origin/video7
  remotes/origin/video8
  remotes/origin/video9

**Comment by tylermcginnis** [comment]
Sorry steps don't coincide with "videos" since the first video is just a slideshow. So "step1" should be "video2" branch.
