### ISSUE TITLE
Quiz: Npm, Babel, and Webpack: Question 2 hangs in Chrome

### ISSUE THREAD

**Issue by DaveLindberg** [ReactjsProgram/React-Fundamentals#44]
Can't progress past Question 2 in this quiz while using Chrome Version 55.0.2883.95 (64-bit): after selecting an answer option, the 'Check' button doesn't function. 

Not an issue in Firefox, where I was able to complete the quiz. Using macOS Sierra 10.12.1.

**Comment by tylermcginnis** [comment]
Hi! Thanks for filing this. As of tomorrow morning, the entire course will have been re-built and re-recorded from scratch. That means that this issue is no longer valid. Thanks again!
