### ISSUE TITLE
GH Pages example app no longer works on new versions of Chrome

### ISSUE THREAD

**Issue by audiolion** [ReactjsProgram/React-Fundamentals#53]
Mixed content requests are now blocked, the weather api is queried over http and the request gets blocked so the GH pages example app doesn't work.

**Comment by tylermcginnis** [comment]
Hi! Thanks for filing this. As of tomorrow morning, the entire course will have been re-built and re-recorded from scratch. That means that this issue is no longer valid. Thanks again!

**Comment by audiolion** [comment]
Oh man! im stoked, going through this a month ago I was transcribing everything to use class transform properties and such which was good practice, but I am also excited to see the other updates!

**Comment by tylermcginnis** [comment]
There's a lot. React Router v4. Classes. prop-types. functional setState. Enjoy!
