### ISSUE TITLE
Install webpack earlier in the lesson

### ISSUE THREAD

**Issue by fjanon** [ReactjsProgram/React-Fundamentals#56]
I think it would be better to show the command to install webpack earlier in the lesson. I had to search through the lesson to find it after some over commands that failed because webpack wasn't installed.

**Comment by tylermcginnis** [comment]
Hi! Thanks for filing this. As of tomorrow morning, the entire course will have been re-built and re-recorded from scratch. That means that this issue is no longer valid. Thanks again!
