### ISSUE TITLE
Remove references to coffeescript that are not needed

### ISSUE THREAD

**Issue by fjanon** [ReactjsProgram/React-Fundamentals#57]
I think that coffeescript has nothing to do with React, and using it as an example is confusing. I would prefer to use Babel from the beginning, so we can execute the npm commands along.

**Comment by tylermcginnis** [comment]
Hi! Thanks for filing this. As of tomorrow morning, the entire course will have been re-built and re-recorded from scratch. That means that this issue is no longer valid. Thanks again!
