### ISSUE TITLE
First React Component: ""

### ISSUE THREAD

**Issue by fjanon** [ReactjsProgram/React-Fundamentals#58]
In the example code:

var HelloWorld = React.createClass({
  displayName: "HelloMessage",
  render: function() {
    return React.createElement("div", null, "Hello World");
  }
});

Why is there 'displayName: "HelloMessage"'?

There is no mention at all of it in the text.

**Comment by tylermcginnis** [comment]
Hi! Thanks for filing this. As of tomorrow morning, the entire course will have been re-built and re-recorded from scratch. That means that this issue is no longer valid. Thanks again!

**Comment by fjanon** [comment]
So when will the new version of the course be available? What will be the url? Thanks

**Comment by tylermcginnis** [comment]
reacttraining.com/online/react-fundamentals
