### ISSUE TITLE
Wrong Repo ES6 course

### ISSUE THREAD

**Issue by jjpaulino** [ReactjsProgram/React-Fundamentals#59]
The repo that we are suppose to clone in the ES6 training is not the same as the one showed in the videos. 
Please, help resolve this issue, so we can code along with you on that training

**Comment by tylermcginnis** [comment]
Hi! Thanks for filing this. As of tomorrow morning, the entire course will have been re-built and re-recorded from scratch. That means that this issue is no longer valid. Thanks again!
