### ISSUE TITLE
How do I use this code?

### ISSUE THREAD

**Issue by rorm** [ReactjsProgram/React-Fundamentals#67]
Apologies for the noob question, but how do I clone the code from the various lessons?

When I use git clone https://github.com/ReactTraining/react-fundamentals.git all I get is a .git folder and the Notes and Readme files.

**Comment by raunaqss** [comment]
After cloning a repo—by default you are on its `master` branch; which contains only `Notes.md` and `README.md` files in this case.

To refer to the code from various lessons checkout to the relevant branch:
`git checkout _branch_name_`

For example, if you want to refer to the final result of this project (and the code for the same), follow this:
```
git checkout hosting
npm install
npm start
```

Branch `hosting` has code for the final chapter of the course. Npm install installs dependencies and npm start will start the dev server and enable you to use the github-battle app on your browser.

**Comment by rorm** [comment]
Thanks so much for your help, Raunaq! This is the help I needed. Cheers
