### ISSUE TITLE
Id of username isn't unique on battle

### ISSUE THREAD

**Issue by sconstantinides** [ReactjsProgram/React-Fundamentals#72]
Since there are two PlayerInput components, their labels & username inputs need unique ids. Could be fixed with something like:

- `htmlFor={this.props.id + 'Username'}`
- `id={this.props.id + 'Username'}`

Thanks for the amazing tutorials! 🎉

**Comment by tylermcginnis** [comment]
This is right, but solving it would be too big of a hassle (having to update videos and all), so going to close this for now.
