### ISSUE TITLE
In Hosting Branch

### ISSUE THREAD

**Issue by nolawi** [ReactjsProgram/React-Fundamentals#73]
`MacBook-Pro ~/g/react-fundamentals-hosting>
npm run firebase init
npm ERR! missing script: firebase

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/user/.npm/_logs/2017-06-17T22_21_34_891Z-debug.log`

not happening like the video

**Comment by tylermcginnis** [comment]
because it's firebase-init not firebase init
