### ISSUE TITLE
ERROR in (webpack)-dev-server/client

### ISSUE THREAD

**Issue by Fettabachi** [ReactjsProgram/React-Fundamentals#78]
When running `npm start` on the `popular` branch I get this error;
```
Module not found: Error: Can't resolve 'loglevel' in '.../react-fundamentals/node_modules/webpack-dev-server/client'
```
found this fix
https://github.com/webpack/webpack-dev-server/issues/1000
`npm i -D loglevel`

**Comment by tylermcginnis** [comment]
Yeah this is an issue with webpack currently. Not much I can do on my end. I'll leave this open until it's fixed.

**Comment by tylermcginnis** [comment]
Another solution is to install the "old" version of webpack-dev-server that is used in the video 

```    "webpack-dev-server": "2.4.2" ```

**Comment by Fettabachi** [comment]
This is what’s currently in package.json "webpack-dev-server": "^2.4.2"
Should I remove the caret?



Thanks,
Tim Fetter

On July 22, 2017 at 2:27:31 PM, Tyler McGinnis (notifications@github.com)
wrote:

Another solution is to install the "old" version of webpack-dev-server that
is used in the video

"webpack-dev-server": "2.4.2"

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/tylermcginnis/react-fundamentals/issues/78#issuecomment-317201638>,
or mute the thread

**Comment by tylermcginnis** [comment]
Yes.

**Comment by tylermcginnis** [comment]
Should be fixed now.
