### ISSUE TITLE
github api bad call

### ISSUE THREAD

**Issue by AndresMartinMaq** [ReactjsProgram/React-Fundamentals#80]
Hey, just letting you know that requesting from https://api.github.com/users/[username]/repos&per_page=100 as it is in the axios branch and video doesn't work (for me and now at least), it needs  "?per_page" and not "&per_page" directly. (https://developer.github.com/v3/#pagination).

Really liking the tutorial btw!

**Comment by tylermcginnis** [comment]
Thanks!
