### ISSUE TITLE
Building for Production and Hosting - package.json in Windows requires different script

### ISSUE THREAD

**Issue by codemv** [ReactjsProgram/React-Fundamentals#85]
Hi tylermcginnis,

For students developing on Windows, the code in package.json for the build script in the video "Building for Production and Hosting" needs to change from:

`"build": "NODE_ENV='production' webpack -p"`

to

`"build": "SET NODE_ENV='production' & webpack -p"`

... at least it did for me before the production project would build and upload. Not sure if you already mention this anywhere already and this is redundant info, but I didn't see it.

Cheers.

**Comment by tylermcginnis** [comment]
Made a comment in the course about this. Thanks!
