### ISSUE TITLE
first-component branch webpack 4 troubles

### ISSUE THREAD

**Issue by michaelyfan** [ReactjsProgram/React-Fundamentals#87]
Hi y'all,

Weird issue when cloning the first-component branch and trying to follow the videos from there. npm update doesn't properly update packages, especially the webpack package (which updates to 2.7.0 and then stays stuck at 2.7.0), so the fixes that Tyler mentions for making the app compatible with webpack 4 instead cause errors. Still trying to make sure this isn't a problem with npm, but I have the latest version. Is anyone else experiencing this issue?

**Comment by tylermcginnis** [comment]
Instead of running npm updated, delete your node_modules folder, change the version of webpack in your package.json, then run `npm install`. See if that fixes it.

**Comment by michaelyfan** [comment]
I noticed you updated the branch -- thanks for doing this. It works as expected now.
