### ISSUE TITLE
Course Issues

### ISSUE THREAD

**Issue by tylermcginnis** [ReactjsProgram/React-Fundamentals#92]
### Example comment

title: Why React?
issue: description of issue.

I'll "hide" the comment when it's fixed.

**Comment by jazztbone2b** [comment]
title: Introduction Philosophy, and Tips
issue: 2 typos 

-> 1. I believe very strongly **_is_** creating a linear approach to learning. is should be **_in_**

-> 6. ... Again, if your code isn’t working after following a video, very carefully compare it **_so_** the specific commit for that video before asking a question in the facebook group. so should be **_to_**

**Comment by jazztbone2b** [comment]
title: (Quiz) The React Ecosystem
issue: The quiz page is empty. All that appears in the module is the title at the top.

**Comment by jurt0001** [comment]
title: Spelling Error
issue: In introduction description, "I believe very strongly is creating a linear approach to learning." - "is" should be "in". 

title: Example project error
issue: In your own example of the project we will be building. there is an error. Cannot read property 'type' of null. here is the URL.  https://competent-tesla-bf9dde.netlify.com/new

**Comment by jurt0001** [comment]
title: NPM Quiz. 
issue: Doesn't give you the correct answer when you have gotten it wrong.

**Comment by jurt0001** [comment]
title: Webpack slide @ 0:16
issue: wrong word - slide reads "Why problem does this tool solve?" Should be "What problem does this tool solve".

**Comment by jurt0001** [comment]
title: Practice (props)
issue: All the codepens open up in the course tab. You should have them automatically open in a new a tab so you don't have to open up your course again. UX problems :p

**Comment by jurt0001** [comment]
Title: URL is being shown when they shouldn't be on (Project) Repositories Grid

Issue: The formatting here is broken. Instead of the work "here" being clickable, the following shows up. 

"The code for this video can be found [here](https://github.com/tylermcginnis/react-course/tree/8-repos-grid). The commit for this video can be found [here](https://github.com/tylermcginnis/react-course/commit/92953a8f3f6f09f32080d0980b57637e7b0a131b)."

**Comment by nripoli4810** [comment]
title: (project) withHover Higher Order Component
issue: Both links for the code / commit for this video take you to branch 23 instead of branch 22

Thanks!

**Comment by tylermcginnis** [comment]
The curriculum requires knowledge of `dangerouslySetInnerHTML` which isn't mentioned in the course.

**Comment by VeikkoLehmuskorpi** [comment]
title: PropTypes
issue: Slide reads "Note that by default, every prop is optional. To make them required, append .required as we did above.", ".required" should be ".isRequired"

**Comment by nripoli4810** [comment]
title: (Bonus) React AHA Moments
issue: In the paragraph under `"Inheritance is unnecessary in React, and both containment and specialization can be achieved with composition."`, the second sentence is missing the word `to`. 

Currently reads: A precedent move away from inheritance...
Should be: A precedent **_to_** move away from inheritance...

**Comment by cjnething** [comment]
title: Everything you should know about NPM
issue: Around the 9:20 mark you're explaining the difference between using ^ and ~ for NPM versions but it looks like all of the examples are using ^

**Comment by belludev** [comment]
title: (Bonus) Imperative vs Declarative Programming
issue: 3rd paragraph towards the end, you used "#preach.s", I want to say it was probably meant to be "#preach." without the s tailing on the end.

**Comment by brandhilton** [comment]
Minor verbal flub in Webpack: A Gentle Introduction, time 6:25

**Comment by brandhilton** [comment]
Webpack: A Gentle Introduction - why is "js" in parens for babel? 
{ test: /\.(js)$/, use: 'babel-loader' }

**Comment by brandhilton** [comment]
Pure Functions: ole' should be ol' (ol' being a contraction of "old")

**Comment by brandhilton** [comment]
PropTypes: "To make them required, append .required as we did above." - should be .isRequired

**Comment by brandhilton** [comment]
The Component Lifecycle: minor verbal flub near 2:25

**Comment by tylermcginnis** [comment]
"Howdy from Austin, Texas! Just an fyi - came across a small typo at the following location: Course: React (beta) Section: "Webpack: A Gentle Introduction" TimeStamp: 00:00:14 Text: "Why problem does this tool solve?" Fix: "What problem(s) does this tool solve?" Like the course so far and keep up the great work!"

**Comment by tylermcginnis** [comment]
"Hey, it seems like there's a missing lesson in the React beta course in the Handling Form State section. (Project) Player Input ends with the PlayerInput component just logging the content to console, but (Project) Render PlayerInput starts with two inputs wired up to pull GitHub avatars etc. Is there something missing or am I just confused?"

**Comment by barelabs** [comment]
Title: The React Ecosystem:

In the video and in text, you state: "Third, no new features of React are making Redux obsolete. Again, I think of **Redux as more of an ecosystem** than anything else. New features to React can replace parts of that ecosystem, but I don’t believe it’ll ever replace the whole thing."

I think you meant to say **"React"** is more of an ecosystem.

**Comment by tylermcginnis** [comment]
@barelabs Nope that's right as it is. Redux is an ecosystem. No individual feature of React will replace Redux's ecosystem.

**Comment by tylermcginnis** [comment]
<img width="685" alt="Screen Shot 2019-04-23 at 12 16 10 PM" src="https://user-images.githubusercontent.com/2933430/59546761-b155db80-8ef0-11e9-92a8-a804fcbb480f.png">

**Comment by barelabs** [comment]
title: (Quiz) The Component Lifecycle

issue: In the question "What lifecycle is good for establishing the initial state of a component?", I believe the answer should just be the "constructor", but the quiz shows two answers as correct.  In addition to the constructor, the quiz is also showing "componentDidUpdate" as being correct.

The quiz is currently marking this question as wrong if both answers are not selected together.

**Comment by barelabs** [comment]
title: (Project) Results Skeleton

issue:  The completed code for the above section points to the wrong commit.  Both links to the code and commit incorrectly point to "12. Player Preview,"  The links should instead point to "13. Results Skeleton."  The correct commit for "13. Results Skeleton" is: 3e4f3903b206b28e0cae9bc181df6dc6f6fd4e0f

**Comment by barelabs** [comment]
title: (Quiz) Render Props

issue:  The second question has the student read code and asks regarding the usage of the Hover component.  The Hover class returns in the render method the following:

`<div onMouseOver={this.mouseOver} onMouseOut={this.mouseOut}>
        {this.props.children(this.state.hovering)}
      </div>`

There are two answer choices regarding the correct usage of the Hover component:

First choice: `<Hover>
  {(hovering) => <DailyChart hovering={hovering}>}
</Hover>`

and second choice:

`<Hover render={(hovering) => <DailyChart hovering={hovering}>} />`

This question is marked wrong unless both answer choices are selected.  Shouldn't there be only one answer (with the first choice being correct), since it is rendering children between the opening and closing tags, or am I missing something?

**Comment by tylermcginnis** [comment]
"For the Results Skeleton Section, the code and Commit are not up to date, they only cover up to the previous Player Preview Video."

**Comment by barelabs** [comment]
title: (Project) 404

issue: There is a minor editing or verbal flub between 2:17 and 2:22.

**Comment by Aka4Code** [comment]
title: React (Beta) - Webpack: A Gentle Introduction
issue:  
Video, timestamp: 9:45
wrong declaration of webpack.EnvironmentPlugin:

![image](https://user-images.githubusercontent.com/11789024/60796895-97658c80-a16e-11e9-8c35-1370a642e070.png)

**There is array:**
        new webpack.EnvironmentPlugin([
            'NODE_ENV': 'production'
        ])

**Should have been object:**
        new webpack.EnvironmentPlugin({
            'NODE_ENV': 'production'
        })

The same issue in the text below video:
![image](https://user-images.githubusercontent.com/11789024/60798559-a994fa00-a171-11e9-8d25-71a7f15332d5.png)

**Comment by Aka4Code** [comment]
title: React (Beta) - Webpack: A Gentle Introduction
issue:
Video, timestamp: 5:19
Comma missing between objects

![image](https://user-images.githubusercontent.com/11789024/60797278-45713680-a16f-11e9-9330-aacc3f3cc192.png)

**Comment by Aka4Code** [comment]
title: React (Beta) - (Project) First Component
issue:
Video, timestamp: 17:14
Wrong wrapping module section inside {}
![image](https://user-images.githubusercontent.com/11789024/60802186-a7826980-a178-11e9-8ba9-7dc504d3432b.png)

See correct: https://webpack.js.org/concepts/

**Comment by Aka4Code** [comment]
title: React (Beta) > Validating Props with PropTypes > PropTypes
issue:
.required or .isRequired ?

![image](https://user-images.githubusercontent.com/11789024/60978000-b875db00-a330-11e9-9482-04fe2e2d216c.png)

**Comment by VeikkoLehmuskorpi** [comment]
> title: React (Beta) > Validating Props with PropTypes > PropTypes
> issue:
> .required or .isRequired ?
> 
> ![image](https://user-images.githubusercontent.com/11789024/60978000-b875db00-a330-11e9-9482-04fe2e2d216c.png)

@Aka4Code [Already reported above](https://github.com/tylermcginnis/react-course/issues/92#issuecomment-495077425), deleting this comment after you've acknowledged it - to keep the thread clean.

**Comment by brandhilton** [comment]
Code Splitting in React

edit.showEdtior() should be edit.showEditor()

**Comment by brandhilton** [comment]
Class Fields

Wel,l should be Well,

**Comment by brandhilton** [comment]
Code Splitting in React

"the last thing we need to do **it** figure out" should be "the last thing we need to do **is** figure out"

**Comment by brandhilton** [comment]
Code Splitting in React

Two errors in the following: "Notice that we’re passing it a function as it’s “children” prop. That means we need to invoke children passing is the component state."
1. "it's" should be "its"
2. "passing is" should be "passing in" or "passing it"

**Comment by brandhilton** [comment]
Building React Apps for Production

"All you need to do **it**" should be ""All you need to do **is**"

**Comment by daniel-farlow** [comment]
title: JSX quiz
issue: The (third) question is, "To render no UI, you return a falsy value from `render`?" The given answer is marked as "false" with the explanation that you should return `null` (or `false`). But aren't these falsy values? According to MDN, these are two of the [seven](https://developer.mozilla.org/en-US/docs/Glossary/Falsy) falsy values in JS. Maybe I misunderstood the question, but I found the wording confusing.

**Comment by daniel-farlow** [comment]
title: the "this" keyword quiz
issue: the third answer option is accidentally merged with the explanation:

<img width="718" alt="this-quiz-issue" src="https://user-images.githubusercontent.com/52146855/68537260-640a5880-032e-11ea-8fe0-ee30f5f85551.png">

**Comment by JonAmparo** [comment]
React > Code Sharing > Higher Order Components 

![Screenshot from 2019-11-14 10-52-06](https://user-images.githubusercontent.com/16710957/68873045-fadb6a00-06cc-11ea-8567-95dce7b95277.png)

Underneath the "Render the “Component” argument passing it a “hovering” prop." section within the code.  Constructor has a param of "super" instead of "props".

Edit: Multiple components have this error of contructor with the param of super instead of props.

**Comment by dekisr** [comment]
**title**: React Context  - https://learn.tylermcginnis.com/courses/react/lectures/9336930
**issue**: typo.

After the first code at **Updating Context State**:
_...Now, anywhere in our component tree, using ThemeContext.Consumer, we can grab locale OR toggleLocale..._

Shoud ThemeContext.Consumer be LocaleContext.Consumer?

**Comment by RSobieszek** [comment]
title: Everything you should know about NPM
issue: npm install paragraph. Backticks are not placed correctly resulting in bad styling of the paragraph. "...track of your dependencies and ``devDependenciesis if someone downloads ..."

**Comment by tylermcginnis** [comment]
https://github.com/tylermcginnis/react-course/commit/2560cfef1e6ea0025d5729f42938903690a64e6e#r39545347

**Comment by nbergeron-seedbox** [comment]
Hi Tyler, 

can you help please ?

in the first video  **(Project) First Component**, when i run _npm run build_, i get an error.

```
npm ERR! code ELIFECYCLE

npm ERR! errno 2
npm ERR! github-battle@1.0.0 build: `webpack`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the github-battle@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/nathaliebergeron/.npm/_logs/2020-07-13T12_56_52_102Z-debug.log
```

**Comment by nbergeron-seedbox** [comment]
you deleted my comments. I am still blocked and I cannot continue the course. Can you help me please ?

**Comment by cjnething** [comment]
@nbergeron-seedbox I saw your earlier question, not an expert but can try. Can you post the full output you received in the terminal? Also if you have a Facebook account there is a group on there for the class that might be helpful for questions like these.

**Comment by nbergeron-seedbox** [comment]
thanks **cjnething**, I fixed my prob. finally.

**Comment by AlbertVilaCalvo** [comment]
title: React Context 
issue: typo

>  React knows if the data changes is by using “reference identity” (which is kind of a fancy way of saving oldObject === newObject).

saving -> saying

**Comment by AlbertVilaCalvo** [comment]
title: Code Splitting with React Router v4
issue: typo + wrong line highlighted on code

> That means we need to invoke children passing is the component state.
 
it -> in or it

And the code that follows this sentence has the highlight on line with `}`, should be at line `return this.props.children(this.state.component)`

**Comment by ChrisTalksTech** [comment]
title:(Project) Player Input
issue: form doesn't render on page

**Comment by naadei-zz** [comment]
title: project-first-component
issue: js syntax

The `module` object is wrapped within an additional object in the video here:

![alt](https://screenshot.click/22-01-c5ss5-ixfe9.png)

It's mentioned further along in the video, maybe a disclaimer in the description would help too as I was following along step-by-step 😅

**Comment by HaiLe** [comment]
I ran into an exception with `npm run start`.  Attached is the stacktrace

```
"devDependencies": {
    "@babel/core": "^7.17.0",
    "@babel/preset-env": "^7.16.11",
    "@babel/preset-react": "^7.16.7",
    "babel-loader": "^8.2.3",
    "css-loader": "^6.6.0",
    "html-webpack-plugin": "^5.5.0",
    "style-loader": "^3.3.1",
    "webpack": "^5.68.0",
    "webpack-cli": "^4.9.2",
    "webpack-dev-server": "^4.7.4"
  }
```

```
hai-mpb-68:hello-react haile$ npm run start

> hello-react@1.0.0 start /Users/haile/proj/hello-react
> webpack serve

[webpack-cli] /Users/haile/proj/hello-react/node_modules/webpack-dev-server/lib/servers/WebsocketServer.js:10
  static heartbeatInterval = 1000;
                           ^

SyntaxError: Unexpected token =
    at new Script (vm.js:85:7)
    at createScript (vm.js:266:10)
    at Object.runInThisContext (vm.js:314:10)
    at Module._compile (internal/modules/cjs/loader.js:698:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
    at Module.load (internal/modules/cjs/loader.js:630:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:570:12)
    at Function.Module._load (internal/modules/cjs/loader.js:562:3)
    at Module.require (internal/modules/cjs/loader.js:667:17)
    at require (internal/modules/cjs/helpers.js:20:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! hello-react@1.0.0 start: `webpack serve`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the hello-react@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/haile/.npm/_logs/2022-02-06T18_19_04_502Z-debug.log
hai-mpb-68:hello-react haile$ 

```

**Comment by thomasmalley** [comment]
title: The Component Lifecycle – Repositories Grid (Project)
issue: _name_ variable unused in ReposGrid 

imho the content of the h2 in line 48 should be `{name}` not ~~{login}~~

My Arguments being: 
* We are fetching & listing **popular repos** not popular users, aren't we? 
* Also `href={html_url}` leads to the repository itself, not the user profile.

**Comment by juagarca** [comment]
title: (PROJECT) PLAYER PREVIEW
issue: the video doesn't seem to load

**Comment by brigdev** [comment]
title: (Bonus) Inheritance vs Composition
issue: lesson content is actually JavaScript Inheritance and the Prototype Chain

I was confused by the fact that I wasn't reading/seeing anything about composition in this lesson, so went back to the Advanced JavaScript course to review my understanding. 

It seems the video and text content on the (Bonus) Inheritance vs Composition lesson is taken from the ["JavaScript Inheritance and the Prototype Chain" lesson](https://ui.dev/c/advanced-javascript/javascript-inheritance-and-the-prototype-chain) in Advanced JavaScript, not from ["JavaScript Composition vs Inheritance"](https://ui.dev/c/advanced-javascript/javascript-inheritance-vs-composition).
