### ISSUE TITLE
Compile errors

### ISSUE THREAD

**Issue by eclectic-coding** [ReactjsProgram/React-Fundamentals#93]
I started having trouble getting 'popular.js` to compile with "Caching Repos" episode. Ther error message at the console is:

```sh
Failed to compile.

./src/components/Popular.js
  Line 63:  'error' is not defined  no-undef
```

Line 63 reads [see here](https://github.com/tylermcginnis/react-course/blob/7eea3416410b51426a468e4dfe9bb247c60d8582/app/components/Popular.js#L61): 
```js
.catch(() => {
          console.warn('Error fetching repos: ', error)
``` 

I think the line should read the following, and it seems to work fine:
```js
.catch(() => {
          console.warn('Error fetching repos: ', this.state.error)
```
Thanks for a great course and I am learning a lot.

**Comment by tylermcginnis** [comment]
Closing since there's another issue about this. Thanks though!
