### ISSUE TITLE
Incorrect CSS attribute in btn class

### ISSUE THREAD

**Issue by eqlz** [ReactjsProgram/React-Fundamentals#96]
Under branch 10-player-input, inside `app/index.css`, https://github.com/tylermcginnis/react-course/blob/10-player-input/app/index.css:

Under this `btn` class: `text-decoration: uppercase;` should have been `text-transform: uppercase;`
```
.btn {
  padding: 10px;
  text-decoration: uppercase;
  letter-spacing: .25em;
  border-radius: 3px;
  border: none;
  font-size: 16px;
  display: flex;
  justify-content: center;
  align-items: center;
  cursor: pointer;
  text-decoration: none;
  max-width: 200px;
}
```

**Comment by tylermcginnis** [comment]
Thank you!
